on:
  project_card:
    types: [moved]

jobs:
  alarm:
    runs-on: macOS-latest
    
    steps:
      - run: |
          cat $GITHUB_EVENT_PATH
#     - run: >-
#         curl -X POST ${{ secrets.SLACK_WEBHOOK_URL_LARANHEE_TEST }}
#         -H 'Content-Type: application/json'
#         -d '{
#           "text": "다음 일정이 정해졌습니다. 2019년 9월 7일 오전 11시"
#         }'
